groups:
  - name: gpu_alerts
    rules:
      - alert: GPUHighTemperature
        expr: gpu_temperature_celsius > 80
        for: 5m
        labels:
          severity: critical
          service: gpu-monitoring
        annotations:
          summary: "GPU Temperature Critical"
          description: "GPU {{ $labels.gpu_name }} ({{ $labels.gpu_index }}) temperature is {{ $value }}°C, which is above the critical threshold of 80°C"

      - alert: GPUVeryHighTemperature
        expr: gpu_temperature_celsius > 85
        for: 1m
        labels:
          severity: emergency
          service: gpu-monitoring
        annotations:
          summary: "GPU Temperature Emergency"
          description: "GPU {{ $labels.gpu_name }} ({{ $labels.gpu_index }}) temperature is {{ $value }}°C, which is critically high and may cause hardware damage"

      - alert: GPUHighPowerConsumption
        expr: gpu_power_watts > 350
        for: 10m
        labels:
          severity: warning
          service: gpu-monitoring
        annotations:
          summary: "GPU High Power Consumption"
          description: "GPU {{ $labels.gpu_name }} ({{ $labels.gpu_index }}) power consumption is {{ $value }}W, which is above normal operating levels"

      - alert: GPUHighUtilization
        expr: gpu_utilization_percent > 95
        for: 15m
        labels:
          severity: warning
          service: gpu-monitoring
        annotations:
          summary: "GPU High Utilization"
          description: "GPU {{ $labels.gpu_name }} ({{ $labels.gpu_index }}) utilization is {{ $value }}% for more than 15 minutes"

      - alert: GPUHighMemoryUsage
        expr: gpu_memory_usage_percent > 90
        for: 10m
        labels:
          severity: warning
          service: gpu-monitoring
        annotations:
          summary: "GPU High Memory Usage"
          description: "GPU {{ $labels.gpu_name }} ({{ $labels.gpu_index }}) memory usage is {{ $value }}%, which may impact performance"

      - alert: GPUCriticalLowFanSpeed
        expr: gpu_fan_speed < 500
        for: 2m
        labels:
          severity: critical
          service: gpu-monitoring
        annotations:
          summary: "GPU Critical Low Fan Speed"
          description: "GPU {{ $labels.gpu_name }} ({{ $labels.gpu_index }}) fan speed is {{ $value }} RPM, which is critically low and may cause overheating"

      - alert: GPUHighFanSpeed
        expr: gpu_fan_speed > 9000
        for: 5m
        labels:
          severity: warning
          service: gpu-monitoring
        annotations:
          summary: "GPU High Fan Speed Warning"
          description: "GPU {{ $labels.gpu_name }} ({{ $labels.gpu_index }}) fan speed is {{ $value }} RPM, indicating high thermal load or cooling system stress"

      # - alert: GPUDown
      #   expr: up{job=~"gpu-monitor-backend-.*"} == 0
      #   for: 1m
      #   labels:
      #     severity: critical
      #     service: gpu-monitoring
      #   annotations:
      #     summary: "GPU Monitoring Service Down"
      #     description: "GPU monitoring service {{ $labels.job }} on {{ $labels.instance }} is down"

      - alert: GPUHealthIssue
        expr: gpu_health_status > 1
        for: 2m
        labels:
          severity: warning
          service: gpu-monitoring
        annotations:
          summary: "GPU Health Issue Detected"
          description: "GPU {{ $labels.gpu_name }} ({{ $labels.gpu_index }}) health status is {{ $value }} (0=Healthy, 1=Caution, 2=Warning, 3=Critical)"
