global:
  resolve_timeout: 5m
  smtp_smarthost: "${SMTP_HOST}"
  smtp_from: "${SMTP_FROM}"
  smtp_auth_username: "${SMTP_USER}"
  smtp_auth_password: "${SMTP_PASS}"
  smtp_require_tls: true
  smtp_auth_identity: "${SMTP_USER}"

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 2m  # Reduced for testing
  receiver: 'critical-alerts'  # default receiver

  routes:
    - match:
        severity: emergency
      group_wait: 5s
      repeat_interval: 1m  # Reduced for testing
      receiver: 'emergency-alerts'
    - match:
        severity: critical
      group_wait: 5s
      repeat_interval: 2m  # Reduced for testing
      receiver: 'critical-alerts'
    - match:
        severity: warning
      group_wait: 5s
      repeat_interval: 2m  # Reduced for testing
      receiver: 'warning-alerts'

receivers:
  - name: 'emergency-alerts'
    email_configs:
      - to: "${EMAIL_TO}"
        send_resolved: true
        html: |
          <h2 style="color: red;">🚨 EMERGENCY GPU Monitor Alert</h2>
          {{ range .Alerts }}
          <div style="border: 2px solid red; padding: 15px; margin: 10px 0; background-color: #ffe6e6;">
            <h3>{{ .Annotations.summary }}</h3>
            <p><strong>Description:</strong> {{ .Annotations.description }}</p>
            <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
            <p><strong>GPU:</strong> {{ .Labels.gpu_name }} (Index: {{ .Labels.gpu_index }})</p>
            <p><strong>Started:</strong> {{ .StartsAt }}</p>
            <p><strong>Status:</strong> {{ .Status }}</p>
          </div>
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: "${EMAIL_TO}"
        send_resolved: true
        html: |
          <h2 style="color: orange;">⚠️ CRITICAL GPU Monitor Alert</h2>
          {{ range .Alerts }}
          <div style="border: 2px solid orange; padding: 15px; margin: 10px 0; background-color: #fff3cd;">
            <h3>{{ .Annotations.summary }}</h3>
            <p><strong>Description:</strong> {{ .Annotations.description }}</p>
            <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
            <p><strong>GPU:</strong> {{ .Labels.gpu_name }} (Index: {{ .Labels.gpu_index }})</p>
            <p><strong>Started:</strong> {{ .StartsAt }}</p>
            <p><strong>Status:</strong> {{ .Status }}</p>
          </div>
          {{ end }}

  - name: 'warning-alerts'
    email_configs:
      - to: "${EMAIL_TO}"
        send_resolved: true
        html: |
          <h2 style="color: #ff8c00;">⚠️ GPU Monitor Warning</h2>
          {{ range .Alerts }}
          <div style="border: 1px solid #ff8c00; padding: 10px; margin: 10px 0; background-color: #ffeaa7;">
            <h3>{{ .Annotations.summary }}</h3>
            <p><strong>Description:</strong> {{ .Annotations.description }}</p>
            <p><strong>GPU:</strong> {{ .Labels.gpu_name }} (Index: {{ .Labels.gpu_index }})</p>
            <p><strong>Started:</strong> {{ .StartsAt }}</p>
          </div>
          {{ end }}
