global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gpu-monitor-backend-nvml'
    static_configs:
      - targets: ['host.docker.internal:9555']
    metrics_path: '/gpu/metric'
    params:
      method: ['nvml']
    scrape_interval: 10s
    scrape_timeout: 10s
  
  - job_name: 'gpu-monitor-backend-bash'
    static_configs:
      - targets: ['host.docker.internal:9555']
    metrics_path: '/gpu/metric'
    params:
      method: ['bash']
    scrape_interval: 10s
    scrape_timeout: 10s
  
  - job_name: 'gpu-monitor-backend-sim'
    static_configs:
      - targets: ['host.docker.internal:9555']
    metrics_path: '/gpu/metric'
    params:
      method: ['sim']
    scrape_interval: 10s
    scrape_timeout: 10s
